### PR TITLE
fix: issue with select for angular not using initial value

### LINKED ISSUE #4076: db-select initial value not set (DB UX 2.0.0)
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [ ] React
- [x] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

With the new release of DB UX 2.0.0 the db-select component no longer displays the initial value and remains empty after the site has finished loading.

Image

If the value is set after the view is initialised (for example with `AfterViewInit`) the initial value is displayed correctly.

### Expected Behaviour

The initial value of the db-select component should be displayd without explicitly setting the value after the view is initialized.

### Screenshots

_No response_

### Browser version

Chrome

### Add any other context about the problem here.

_No response_

### PR DESCRIPTION
**Pull request by nmerget**
## Proposed changes

closes #4076

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (fix on existing components or architectural decisions)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

File: packages/components/scripts/post-build/components.ts [hunk 1]
```diff
@@ -222,11 +222,19 @@ export const getComponents = (): Component[] => [
...
 		}
 	},
-
 	{
 		name: 'select',
 		overwrites: {
-			angular: [{ from: '<HTMLElement>', to: '<HTMLSelectElement>' }],
+			angular: [
+				{ from: '<HTMLElement>', to: '<HTMLSelectElement>' },
+				// TODO: We can move this to onMount with useTarget after https://github.com/BuilderIO/mitosis/pull/1750 is merged
```
Comment (mfranzke) [inline packages/components/scripts/post-build/components.ts:230]: We can move this to onMount with useTarget after https://github.com/BuilderIO/mitosis/pull/1750 is merged

File: packages/components/scripts/post-build/components.ts [hunk 2]
```diff
@@ -222,11 +222,19 @@ export const getComponents = (): Component[] => [
...
+				{
+					from: 'ngAfterViewInit() {',
+					to:
+						'ngAfterViewInit() {\n' +
+						'\t  this.writeValue(this.value());'
+				}
```
Comment (mfranzke) [inline packages/components/scripts/post-build/components.ts:236]: We can move this to onMount with useTarget after https://github.com/BuilderIO/mitosis/pull/1750 is merged

**Review by mfranzke — APPROVED** [review]
